### ISSUE TITLE
Undefined variable: minimum_emp_PT en v 1.7.4 

### ISSUE THREAD

**Issue by loclamor** [OGSteam/mod-autonomie#6]
Bonjour,

Après la mise à jour du mod en version 1.7.4 , j'ai les notices suivantes qui sont affichées :

```
Notice: Undefined variable: minimum_emp_PT in /srv/www/ogspy.fr/winners/mod/autonomie/fonctions.php on line 423

Notice: Undefined variable: maximum_emp_PT in /srv/www/ogspy.fr/winners/mod/autonomie/fonctions.php on line 425

Notice: Undefined variable: minimum_emp_GT in /srv/www/ogspy.fr/winners/mod/autonomie/fonctions.php on line 428

Notice: Undefined variable: maximum_emp_GT in /srv/www/ogspy.fr/winners/mod/autonomie/fonctions.php on line 429
```
Et les tableaux de la page sont vides ensuite. 

Je suis sous OGSpy 3.3.6.

**Comment by satepestage** [comment]
Bonjour,

Je n'arrive pas à reproduire ton problème pour l'instant.
Quand tu dis que les tableaux de la page sont vides. Ce sont tous les tableaux qui sont impactés ?

**Comment by darknoon29** [comment]
Je peux supprimer l'affichage des notices ^^

**Comment by satepestage** [comment]
La seule raison que je vois là comme ça pour que les variables ne soient pas initialisées c'est qu'il n'y ait pas colonie.

**Comment by loclamor** [comment]
En effet, c'est quand je me connecte avec le compte admin du serveur :)

**Comment by loclamor** [comment]
![image](https://user-images.githubusercontent.com/3027144/77174160-eb2bc200-6ac0-11ea-9bfa-f17995c60d29.png)
Par contre il y a quelques valeurs... incongrues dans ce qui est affiché !

**Comment by satepestage** [comment]
C'est normal d'avoir besoin de tant de transporteur quand on a un hangar de métal au niveau 274.

**Comment by loclamor** [comment]
Ah oui, mais je n'ai pas ces niveaux la :
![Screenshot_20200322-211512](https://user-images.githubusercontent.com/3027144/77259536-67b9ce80-6c82-11ea-9772-4bd638d6bc47.png)

**Comment by satepestage** [comment]
Le nombre de foreuses s'est retrouvé dans le hangar de métal.
Est-ce que tu as les mêmes informations dans la partie Espace Personnel ?
(C'est pour savoir si le problème vient du mod ou des données entrées en base)

**Comment by loclamor** [comment]
Oui, c'est en effet la même chose, donc le problème ne vient pas du mod du coup :)

Par contre sur certaines colonies les bonnes valeurs sont revenues (malgré la présence de foreuses)

**Comment by satepestage** [comment]
Les foreuses ont été pris en compte plus tard par Xtense.
Le fait que les foreuses se sont retrouvées à la place du hangar doit provenir d'une ancienne donnée avant la publication de la mise à jour du client Xtense.
Je vais clôturer cette remonté de bug.

De toutes façons, je suis en préparation d'une version pour prendre en charge les foreuses dans le calcul de la production (ce qui n'est pas encore le cas).
